//
//  MaskType.swift
//  AemiSDR
//

import CoreGraphics
import CoreImage
import Foundation

/// Mask shapes and gradients used for variable blur and alpha masking.
/// Each case maps to a dedicated, optimized shader.
public enum MaskType: Sendable, Equatable, Hashable, CaseIterable {
    /// Linear gradient: top is masked/blurred; bottom is clear.
    case linearTopToBottom

    /// Linear gradient: bottom is masked/blurred; top is clear.
    case linearBottomToTop

    /// Standard rounded rectangle (SDF) with crisp edges.
    case roundedRectangle

    /// Rounded rectangle with eased corner transitions.
    case easedRoundedRectangle

    /// Mathematical superellipse (squircle).
    case superellipseSquircle

    /// Superellipse with eased edge transitions.
    case easedSuperellipseSquircle

    /// Quadratic ease-in gradient: top is masked/blurred; bottom is clear.
    case easeInTopToBottom

    /// Quadratic ease-in gradient: bottom is masked/blurred; top is clear.
    case easeInBottomToTop

    /// Constant alpha mask (all 1.0) for uniform blur intensity.
    case uniform

    /// Quadratic ease-in spotlight gradient on the Y-axis: both top and
    /// bottom edges are masked/blurred and the gradient fades inward to
    /// a clear horizontal centre. The mask is generated by inverting the
    /// underlying centre-proximity field so the public
    /// `verticalCenterBlur` modifier reads as "spotlight" (focus at
    /// centre, blur at edges).
    case easeInCenterVertical

    /// Linear gradient: left is masked/blurred; right is clear.
    case linearLeftToRight

    /// Linear gradient: right is masked/blurred; left is clear.
    case linearRightToLeft

    /// Quadratic ease-in gradient: left is masked/blurred; right is clear.
    case easeInLeftToRight

    /// Quadratic ease-in gradient: right is masked/blurred; left is clear.
    case easeInRightToLeft

    /// Quadratic ease-in spotlight gradient on the X-axis: leading and
    /// trailing edges are masked/blurred and the gradient fades inward
    /// to a clear vertical centre. See `easeInCenterVertical` for the
    /// same rationale on the Y-axis — both cases hardcode the kernel's
    /// `inverted` flag so the `*CenterBlur` modifiers read as a
    /// spotlight (focus at centre, blur at edges).
    case easeInCenterHorizontal

    // MARK: - Convenience Initializer

    /// Creates a MaskType from a corner style and transition algorithm.
    ///
    /// - Parameters:
    ///   - cornerStyle: The corner style to use (.circular or .continuous)
    ///   - transition: The transition algorithm (.linear or .eased)
    public init(cornerStyle: RoundedCornerStyle, transition: TransitionAlgorithm) {
        self = switch (cornerStyle, transition) {
        case (.circular, .linear): .roundedRectangle
        case (.circular, .eased): .easedRoundedRectangle
        case (.continuous, .linear): .superellipseSquircle
        case (.continuous, .eased): .easedSuperellipseSquircle
        @unknown default: .easedSuperellipseSquircle
        }
    }
}

// MARK: - Kernel Descriptor

extension MaskType {
    /// Returns the kernel and arguments needed to generate a mask of this type.
    ///
    /// Centralizes the switch logic previously duplicated in AlphaMaskUIView and VariableBlurUIView.
    ///
    /// - Parameters:
    ///   - size: The view size in points
    ///   - scale: The display scale factor
    ///   - startOffset: Start offset for gradient masks
    ///   - cornerRadius: Corner radius for shape masks
    ///   - fadeWidth: Fade width for shape masks
    ///   - inverted: Whether to invert the mask
    /// - Returns: A tuple of (kernel, arguments) ready for `CIKernelCache.generateCGImage`
    func kernelDescriptor(
        size: CGSize,
        scale: CGFloat,
        startOffset: CGFloat = 0,
        cornerRadius: CGFloat = 0,
        fadeWidth: CGFloat = 16,
        inverted: Bool
    ) -> (kernel: CIColorKernel?, arguments: [Any]) {
        let scaledWidth = max(1, ceil(size.width * scale))
        let scaledHeight = max(1, ceil(size.height * scale))
        let inv: Double = inverted ? 1.0 : 0.0

        switch self {
        case .linearTopToBottom:
            return (CIKernelCache.linearMask,
                    [scaledWidth, scaledHeight, startOffset, inverted ? 1.0 : 0.0])

        case .linearBottomToTop:
            return (CIKernelCache.linearMask,
                    [scaledWidth, scaledHeight, startOffset, inverted ? 0.0 : 1.0])

        case .easeInTopToBottom:
            return (CIKernelCache.easeInAlphaMask,
                    [scaledWidth, scaledHeight, startOffset, 0.0, inv])

        case .easeInBottomToTop:
            return (CIKernelCache.easeInAlphaMask,
                    [scaledWidth, scaledHeight, startOffset, 1.0, inv])

        case .roundedRectangle:
            let cr = cornerRadius * scale
            let fw = fadeWidth * scale
            return (CIKernelCache.roundedRectAlphaMask,
                    [scaledWidth, scaledHeight, cr, fw, inv])

        case .easedRoundedRectangle:
            let cr = cornerRadius * scale
            let fw = fadeWidth * scale
            return (CIKernelCache.roundedRectEaseAlphaMask,
                    [scaledWidth, scaledHeight, cr, fw, inv])

        case .superellipseSquircle:
            let cr = cornerRadius * scale
            let fw = fadeWidth * scale
            return (CIKernelCache.superellipseAlphaMask,
                    [scaledWidth, scaledHeight, cr, fw, 2, inv])

        case .easedSuperellipseSquircle:
            let cr = cornerRadius * scale
            let fw = fadeWidth * scale
            return (CIKernelCache.superellipseEaseAlphaMask,
                    [scaledWidth, scaledHeight, cr, fw, 2, inv])

        case .uniform:
            return (CIKernelCache.uniformMask,
                    [scaledWidth, scaledHeight])

        case .easeInCenterVertical:
            // Caller-controlled inversion: the underlying field peaks at
            // the vertical centre and falls to zero at top/bottom edges.
            // Whether that becomes "blur at centre" or "blur at edges" /
            // "reveal at centre" or "reveal at edges" depends on the
            // consumer's alpha convention — variable blur (alpha=1→blur)
            // passes `inverted: true` to get the spotlight pattern;
            // SwiftUI .mask (alpha=1→reveal) leaves `inverted: false`.
            return (CIKernelCache.easeInCenterMask,
                    [scaledWidth, scaledHeight, startOffset, inv])

        case .linearLeftToRight:
            return (CIKernelCache.linearMaskHorizontal,
                    [scaledWidth, scaledHeight, startOffset, inverted ? 1.0 : 0.0])

        case .linearRightToLeft:
            return (CIKernelCache.linearMaskHorizontal,
                    [scaledWidth, scaledHeight, startOffset, inverted ? 0.0 : 1.0])

        case .easeInLeftToRight:
            return (CIKernelCache.easeInAlphaMaskHorizontal,
                    [scaledWidth, scaledHeight, startOffset, 0.0, inv])

        case .easeInRightToLeft:
            return (CIKernelCache.easeInAlphaMaskHorizontal,
                    [scaledWidth, scaledHeight, startOffset, 1.0, inv])

        case .easeInCenterHorizontal:
            // X-axis mirror of `.easeInCenterVertical`: caller controls
            // inversion. See the vertical case for the convention notes.
            return (CIKernelCache.easeInCenterMaskHorizontal,
                    [scaledWidth, scaledHeight, startOffset, inv])
        }
    }
}

// MARK: - Shared Mask Cache

/// Hashable description of a generated mask image.
///
/// Shared between `AlphaMaskUIView` and `VariableBlurUIView` so two views with
/// identical configuration (a list of cells, for example) reuse a single
/// rendered `CGImage` instead of regenerating per-instance.
///
/// Floating-point fields are quantised to integer ticks at a uniform precision
/// of `10_000`. For the typical input ranges (`[0, 1]` for offsets/scales and
/// pixel-bounded values for dimensions/radii) this is well below visual
/// significance and below the noise floor of `CGRect` jitter.
struct MaskCacheKey: Hashable {
    var widthPx: Int
    var heightPx: Int
    var scaleQ: Int
    var maskType: MaskType
    var startOffsetQ: Int
    var cornerRadiusQ: Int
    var fadeWidthQ: Int
    var inverted: Bool

    static func make(
        size: CGSize,
        scale: CGFloat,
        maskType: MaskType,
        startOffset: CGFloat,
        cornerRadius: CGFloat,
        fadeWidth: CGFloat,
        inverted: Bool
    ) -> MaskCacheKey {
        let widthPx = max(1, Int(ceil(size.width * scale)))
        let heightPx = max(1, Int(ceil(size.height * scale)))
        return MaskCacheKey(
            widthPx: widthPx,
            heightPx: heightPx,
            scaleQ: quantize(scale),
            maskType: maskType,
            startOffsetQ: quantize(startOffset),
            cornerRadiusQ: quantize(cornerRadius),
            fadeWidthQ: quantize(fadeWidth),
            inverted: inverted
        )
    }

    private static let quantizePrecision: CGFloat = 10_000

    private static func quantize(_ value: CGFloat) -> Int {
        Int((value * quantizePrecision).rounded())
    }
}

/// Object wrapper so `MaskCacheKey` can serve as an `NSCache` key.
final class MaskCacheKeyBox: NSObject {
    let key: MaskCacheKey
    init(_ key: MaskCacheKey) { self.key = key }

    override var hash: Int { key.hashValue }
    override func isEqual(_ object: Any?) -> Bool {
        guard let other = object as? MaskCacheKeyBox else { return false }
        return other.key == key
    }
}

/// Process-wide mask cache.
///
/// `NSCache` evicts under memory pressure and is thread-safe by contract.
/// A modest count limit caps worst-case retention; mask images are small
/// (single-channel alpha, bounded by view size) so the upper bound on
/// memory is comfortable.
enum MaskCache {
    nonisolated(unsafe) static let storage: NSCache<MaskCacheKeyBox, CGImage> = {
        let cache = NSCache<MaskCacheKeyBox, CGImage>()
        cache.countLimit = 32
        return cache
    }()

    /// Returns the cached image for `key`, generating and inserting one on miss.
    static func image(for key: MaskCacheKey, generate: () -> CGImage?) -> CGImage? {
        let box = MaskCacheKeyBox(key)
        // `NSCache` is documented thread-safe; the strict-memory-safety check
        // can't see that contract, so opt in explicitly here.
        if let cached = unsafe storage.object(forKey: box) { return cached }
        guard let image = generate() else { return nil }
        unsafe storage.setObject(image, forKey: box)
        return image
    }

    /// Returns the cached image for `key` without generating one on miss.
    /// Useful when the caller wants to take a different (e.g. async) path
    /// for the generation step.
    static func peek(for key: MaskCacheKey) -> CGImage? {
        let box = MaskCacheKeyBox(key)
        return unsafe storage.object(forKey: box)
    }

    /// Stores `image` under `key`. Intended for callers that produced the
    /// image off the main thread and need to publish it back into the cache.
    static func insert(_ image: CGImage, for key: MaskCacheKey) {
        let box = MaskCacheKeyBox(key)
        unsafe storage.setObject(image, forKey: box)
    }
}
